# Generated by Django 3.2.4 on 2021-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_name', models.CharField(max_length=200, verbose_name='името на отбор')),
                ('team2_name', models.CharField(max_length=200)),
                ('date_match', models.CharField(max_length=200)),
            ],
        ),
    ]
