# Generated by Django 3.2.4 on 2021-08-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='date_match',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team1_name',
            field=models.CharField(max_length=200),
        ),
    ]
