# Generated by Django 3.2.4 on 2021-08-06 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_teamsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsinfo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
