# Generated by Django 3.2.4 on 2021-08-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matches_matchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
