# Generated by Django 3.2.4 on 2021-08-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_matches_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsinfo',
            name='date',
            field=models.IntegerField(),
        ),
    ]
